# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'NetPictures' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetPictures
	pod 'AFNetworking'
	pod 'MBProgressHUD'
	pod 'MJRefresh'
  target 'NetPicturesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetPicturesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
